org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=34

# Chaquopy settings
chaquopy.extra_packages=PyMuPDF==1.22.5,pdfminer.six==20221105,Pillow==9.5.0,numpy==1.24.3,opencv-python-headless==4.8.0.74,arabic-reshaper==3.0.0,python-bidi==0.4.2,langdetect==1.0.9,pandas==2.0.3,loguru==0.7.2
